# Rename this file to languages.toml to enable multilingual support
[en]
    languageName      = "English"
    languagedirection = "ltr"
    title             = "Example Site"
    weight            = 2
[zh]
    languageName      = "中文"
    languagedirection = "ltr"
    title             = "文渊阁"
    weight            = 1
